name: node-release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - run: npm i -g npm
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm run test

      - name: npm publish - node
        run: npm publish --access public --tag latest
        working-directory: ./dist/node
        env:
          NODE_AUTH_TOKEN: ${{secrets.Z_NPM_TOKEN}}

      - name: npm publish - umd
        run: npm publish --access public --tag latest
        working-directory: ./dist/umd
        env:
          NODE_AUTH_TOKEN: ${{secrets.Z_NPM_TOKEN}}

      - name: npm publish - es5
        run: npm publish --access public --tag latest
        working-directory: ./dist/es5
        env:
          NODE_AUTH_TOKEN: ${{secrets.Z_NPM_TOKEN}}

      - name: npm publish - es6
        run: npm publish --access public --tag latest
        working-directory: ./dist/es6
        env:
          NODE_AUTH_TOKEN: ${{secrets.Z_NPM_TOKEN}}

      - name: npm publish - deno
        run: npm publish --access public --tag latest
        working-directory: ./dist/deno
        env:
          NODE_AUTH_TOKEN: ${{secrets.Z_NPM_TOKEN}}
